In [3]:
import numpy as np
from scipy.signal import convolve2d
input_file = "test.txt"
input_file = "input.txt"

g = np.array([list(map(int,list(x))) for x in open(input_file).read().splitlines()],dtype=int)

fc = 0
s = 0
while True:
    g += 1
    done = False
    while not done:
        fp = (g >= 10)
        fc += np.sum(fp)   
        flash = convolve2d(fp,np.ones((3,3), dtype=int),mode='same')
        ng = g+flash
        ng[fp] = -10
        if (ng == g).all():
            done = True
        g = ng
    if s == 100:
        print(fc)
    g[g<0] = 0
    if (g==0).all():
        break
    s += 1

print(s+1)


1595
437


In [20]:
import numpy as np
from scipy.signal import convolve2d



g = np.zeros((10,10))
g[5,4] = 1
f = np.ones((3,3))
print(f)
print(g)

print(convolve2d(g,f, mode='same'))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
