In [20]:
import numpy as np
from scipy.signal import convolve2d
input_file = "test.txt"
input_file = "input.txt"

g = np.array([list(map(int,list(x))) for x in open(input_file).read().splitlines()],dtype=int)

r = [0,0]
while (g != 0).any():
    g += 1
    done = False
    while not done:
        r[0] += 0 if r[1] >= 100 else np.sum(g >= 10)   
        ng = g + convolve2d(g >= 10,np.ones((3,3), dtype=int),mode='same')
        ng[g >= 10] = -10
        done = True if (ng == g).all() else False
        g = ng
    g[g<0] = 0
    r[1] += 1

print(r)


[1595, 437]


In [20]:
import numpy as np
from scipy.signal import convolve2d



g = np.zeros((10,10))
g[5,4] = 1
f = np.ones((3,3))
print(f)
print(g)

print(convolve2d(g,f, mode='same'))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
